#!/bin/bash
# linux-dev one-time initializations

echo -e "\n===========> configuring time zone...\n"
sudo dpkg-reconfigure tzdata 2>/dev/null

echo -e "\n===========> default locale is $LANG; to change it, run 'sudo dpkg-reconfigure locales'\n"
